# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Deno

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS
    env:
      JHI_E2E_HEADLESS: true
      HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      

    strategy:
      matrix:
        deno: ["v1.x", "nightly"]
        os: [ubuntu-latest]
   
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with:
            node-version: 14.16.1
     - uses: actions/setup-java@v1
       with:
           java-version: '11.0.11'
     - name: Install node.js packages
       run: npm install
       
     #- name: test_front
     #  run: npm run ci:frontend:test
       
     #- name: test_back
     #  run: chmod +x mvnw && npm run ci:backend:test
       
     - name: test_crea_serv
       run: ./mvnw -ntp verify -DskipTests --batch-mode "-Pprod" "-Pe2e" "-Denforcer.skip=true"*
       
     #- name: test_E2E_prepare
     #  run: npm run ci:e2e:prepare:docker
       
     #- name: test_E2E_run
     #  run: npm run ci:e2e:run
       
     #- name: test_E2E_end
     #  run: npm run ci:e2e:teardown
       
     - name: deploiement_eroku
       run: ./mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=test-richard-68320
       
       
       
       
       
       
   
